# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'IraqPayment' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for IraqPayment

  pod 'Firebase/Core'
  pod 'Firebase/Messaging'

  target 'IraqPayment-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'

    pod 'CodePush', :path => '../node_modules/react-native-code-push'

    pod 'RNI18n', :path => '../node_modules/react-native-i18n'

    pod 'react-native-date-picker', :path => '../node_modules/react-native-date-picker'

    pod 'TouchID', :path => '../node_modules/react-native-touch-id'

  end

  target 'IraqPaymentTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

