const HOME_HEADER_COLOR = "#E91E63";
const STATUS_BAR_COLOR = "#1a1b1f";
const HEADER_COLOR = "#252631";
const BACKGROUND_COLOR = "#2b2d42";
const WHITE = "#FFFFFF";
const BLACK = "#000000";
const GRAY = "#DDDDDD";
const RED = "#FF0000";
const GREEN = "#278E43";
const WARNING = "#FFC107";
const DISABLE_COLOR = "#CCCCCC";
const GRAY_ROW = "#DCDCDC";
const BUTTON_COLOR = "#0095d9";
const MODAL_COLOR = "#011627";
const MODAL_ERROR = "#850611";
const MODAL_SUCCESS = "#278E43";
const MODAL_HOME = "#00AAFF";
const SIGN_IN_CARD_INFO = "#8D99AE";
const MY_CARD_COLOR = "#7FA8F0";
const PROFILE_FIELDS = "#3F3F44";
const ERROR_ICON = "#FF0000";
const ASIACELL_COLOR = "#CF0F42";
const KOREK_COLOR = "#0199DC";
const ZAIN_COLOR = "#6DC8B7";
const SOCIAL_MEDIA_UNDERLAY_COLOR = "#FDFFFC";
const SIDEBAR_COLOR = "#777777";
const SIM_CHARGE_2_UNDERLAY_COLOR = "#F3F3F3";
const SIM_CHARGE_2_OTHER_COLOR = "#857CB5";
const SPINNER_COLOR = "#0095d9"; //'#D90429';
const HOME_TOP_COLOR = "#ececec";
const WELCOME_COLOR_1 = "#F03A47";
const WELCOME_COLOR_2 = "#E1BC29";
const WELCOME_COLOR_3 = "#3BB273";

const LIGHT_BLACK = "#333333";
const LIGHTER_BLACK = "#9e9e9e";
const BLACK_BORDER = "#979797";
const BLACK_TAB = "#838383";
const RED_BUTTONS = "#d0302c";
const GREEN_BUTTONS = "#345FB0";
const BLUE_BUTTONS = "#485ea8";
const LIGHT_WHITE = "#fbfbfb";
const SELECT_LANGUAGE_BORDER_COLOR = "#4a90e2";
const UNDERLINE_BORDER_TEXTINPUT_COLOR = "#eaf2f3";
const TAB_BAR_BORDER_COLOR = "#cccccc";
const TITLE_COLOR = "#f7f9e8";
const TRANSACTION_GREEN_COLOR = "#15a649";
const TRANSACTION_RED_COLOR = "#d0021b";
const SUCCESS_MODAL_COLOR = "#25ae88";
const WARNING_MODAL_COLOR = "#FFA500";

export default {
  HOME_HEADER_COLOR,
  BACKGROUND_COLOR,
  WHITE,
  BUTTON_COLOR,
  MODAL_ERROR,
  SIGN_IN_CARD_INFO,
  MODAL_SUCCESS,
  MODAL_HOME,
  DISABLE_COLOR,
  HEADER_COLOR,
  MODAL_COLOR,
  MY_CARD_COLOR,
  BLACK,
  PROFILE_FIELDS,
  ERROR_ICON,
  GRAY,
  ASIACELL_COLOR,
  KOREK_COLOR,
  ZAIN_COLOR,
  GRAY_ROW,
  STATUS_BAR_COLOR,
  SOCIAL_MEDIA_UNDERLAY_COLOR,
  SIDEBAR_COLOR,
  SIM_CHARGE_2_UNDERLAY_COLOR,
  SIM_CHARGE_2_OTHER_COLOR,
  SPINNER_COLOR,
  RED,
  GREEN,
  WARNING,
  HOME_TOP_COLOR,
  WELCOME_COLOR_1,
  WELCOME_COLOR_2,
  WELCOME_COLOR_3,
  SELECT_LANGUAGE_BORDER_COLOR,
  LIGHT_BLACK,
  RED_BUTTONS,
  GREEN_BUTTONS,
  LIGHT_WHITE,
  LIGHTER_BLACK,
  UNDERLINE_BORDER_TEXTINPUT_COLOR,
  TAB_BAR_BORDER_COLOR,
  TITLE_COLOR,
  BLACK_BORDER,
  TRANSACTION_GREEN_COLOR,
  TRANSACTION_RED_COLOR,
  BLACK_TAB,
  SUCCESS_MODAL_COLOR,
  BLUE_BUTTONS,
  WARNING_MODAL_COLOR
};
